#' Estimate the mutation rate from a cohort of tumors with age information
#' @description
#' This function fits a linear model to infer the mutation rate from the
#' relationship between age at diagnosis and mutational burden at MRCA. The
#' model assumes a constant mutation rate prior to the MRCA and comparable
#' tumor growth rates between individuals. Accordingly, the mutational burden
#' per Mb at MRCA is Poisson distributed around $$\mu t_\mathrm{MRCA}$$, where
#' $$\mu$$ is the mutation rate per Mb and $t_\mathrm{MRCA}$$ is the time at
#' which the MRCA emerges.
#' @param lachesis output generated from \code{\link{LACHESIS}}
#' @return mean, standard deviation and 95% confidence interval for the tumor
#' growth time and the mutation rate (per Mb), along with goodness of fit
#' (R squared).
#' @examples
#' # An example file with sample annotations and meta data
#' input.files <- system.file("extdata", "Sample_template.txt",
#'     package = "LACHESIS"
#' )
#' input.files <- data.table::fread(input.files)
#'
#' # cnv and snv files for example tumors
#' nbe11 <- list.files(system.file("extdata/NBE11/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe15 <- list.files(system.file("extdata/NBE15/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe26 <- list.files(system.file("extdata/NBE26/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#'
#' cnv.file <- c(nbe11[1], nbe15[1], nbe26[1])
#' snv.file <- c(nbe11[2], nbe15[2], nbe26[2])
#'
#' input.files$cnv.file <- cnv.file
#' input.files$snv.file <- snv.file
#'
#' # Make an example input file with paths to cnv and snv file along with other
#' # meta data
#' lachesis_input <- tempfile(
#'     pattern = "lachesis", tmpdir = tempdir(),
#'     fileext = ".tsv"
#' )
#' data.table::fwrite(x = input.files, file = lachesis_input, sep = "\t")
#'
#' # Example with template file with paths to multiple cnv/snv files as an input
#' lachesis <- LACHESIS(input.files = lachesis_input)
#' estimateMutationRate(lachesis)
#'
#' @export
#' @import ggplot2
#' @import data.table

estimateMutationRate <- function(lachesis = NULL) {
  res <- ci <- r2 <- slope <- mu <- mu_ci <- . <- NULL

  if (is.null(lachesis)) {
    stop(
      "Missing input. Please provide output generated by LACHESIS."
    )
  }

  if (is.null(lachesis[,Age]) | nrow(lachesis[!is.na(Age),]) == 0 ) {
    stop("Please specify age information.")
  }
  lachesis <- lachesis[!is.na(Age),]

  # fit linear model
  res <- lachesis[,lm(Age ~ MRCA_time_mean)]
  ci <- confint(res, level = 0.95)

  # calculate goodness of fit
  r2 <- summary(res)
  r2 <- r2$r.squared

  # plot the fit
  p <- ggplot(lachesis, aes(x = MRCA_time_mean, y = Age)) +
    geom_point() +  geom_smooth(method='lm') + theme_classic() +
    scale_x_continuous("Number of SNVs per Mb at MRCA") +
    scale_y_continuous("Age at diagnosis")

  slope <- coef(res)["MRCA_time_mean"]

  # the mutation rate is the inverse of the slope
  mu <- 1 / slope
  mu_ci <- rev(1 / ci["MRCA_time_mean", ])

  res <- data.table::data.table(
    Parameter = c("Growth time", "Mutation rate"),
    `2.5 %` = c(
      ci["(Intercept)", 1],
      mu_ci[1]
    ),
    Mean = c(
      coef(res)["(Intercept)"],
      mu
    ),
    `97.5 %` = c(
      ci["(Intercept)", 2],
      mu_ci[2]
    )
  )


  return(list(parameters = res, r.squared = r2, plot = p))
}
