#' Correlate SNV density at ECA/MRCA with clinical parameters such as age, OS,
#'  etc.
#' @description
#' Takes SNV densities as computed by `LACHESIS` as input and correlates them
#' with clinical data such as age at diagnosis, survival data etc.
#' @param lachesis output generated from \code{\link{LACHESIS}}.
#' @param clin.par the clinical parameter used for correlation. Default `Age`.
#' @param clin.suppress.outliers shall outliers (defined as the 2.5% tumors with
#'  lowest and highest densities) be plotted? Default `FALSE`.
#' @param clin.log.densities plot logarithmic densities. Default `FALSE`.
#' @param mut.snv.rate optional; rate of accumulated SNVs per day in a
#' diploid genome (i.e. 3.2 SNVs/day in neuroblastoma)
#' @param corr.time.scale numeric value by which survival time is to be divided
#' to convert into months (e.g., 30 for converting days into months), defaults
#' to `1`.
#' @param lach.col.zero optional, color for single-copy SSNV densities.
#' @param lach.col.multi optional, color for multi-copy SSNV densities.
#' @param output.file optional; file path to output.
#' @return graph with SNV density at ECA/ MRCA compared to clinical parameters
#' @examples
#' # An example file with sample annotations and meta data
#' input.files <- system.file("extdata", "Sample_template.txt",
#'     package = "LACHESIS"
#' )
#' input.files <- data.table::fread(input.files)
#'
#' # cnv and snv files for example tumors
#' nbe11 <- list.files(system.file("extdata/NBE11/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe15 <- list.files(system.file("extdata/NBE15/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe26 <- list.files(system.file("extdata/NBE26/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#'
#' cnv.file <- c(nbe11[1], nbe15[1], nbe26[1])
#' snv.file <- c(nbe11[2], nbe15[2], nbe26[2])
#'
#' input.files$cnv.file <- cnv.file
#' input.files$snv.file <- snv.file
#'
#' # Make an example input file with paths to cnv and snv file along with other
#' # meta data
#' lachesis_input <- tempfile(
#'     pattern = "lachesis", tmpdir = tempdir(),
#'     fileext = ".tsv"
#' )
#' data.table::fwrite(x = input.files, file = lachesis_input, sep = "\t")
#'
#' # Example with template file with paths to multiple cnv/snv files as an input
#' lachesis <- LACHESIS(input.files = lachesis_input)
#' plotClinicalCorrelations(lachesis)
#' @export
#' @importFrom graphics abline Axis box grid hist mtext par rect text title
#' arrows points
#' @importFrom stats cor

plotClinicalCorrelations <- function(lachesis = NULL, clin.par = "Age",
                                     clin.suppress.outliers = FALSE,
                                     clin.log.densities = FALSE,
                                     corr.time.scale = 1, mut.snv.rate = 3.2,
                                     lach.col.multi = "#176A02",
                                     lach.col.zero = "#4FB12B",
                                     output.file = NULL) {
  ECA_time_mean <- MRCA_time_mean <- NULL

  if (!clin.par %in% colnames(lachesis)) {
    stop(clin.par, " not found!")
  }
  if (is.null(lachesis)) {
    stop("Missing input. Please provide the output generated by LACHESIS()")
  }
  if (any(is.na(lachesis$MRCA_time_mean))) {
    tmp1 <- sum(is.na(lachesis$MRCA_time_mean))
    warning(sprintf(
      "Removing %s samples with missing MRCA density estimate.", tmp1
    ))
    rm(tmp1)
    lachesis <- lachesis[!is.na(MRCA_time_mean), ]
  }
  if (nrow(lachesis) == 0) {
    warning(
      "No sample with MRCA density estimate provided. Returning zero."
    )
    return(NULL)
  }
  if (!is.null(output.file)) {
    pdf(output.file, width = 8, height = 6)
  }

  lo_mat <- matrix(data = c(1, 2), nrow = 1, ncol = 2, byrow = TRUE)
  graphics::layout(mat = lo_mat, widths = c(1, 1), heights = c(1, 1))

  to.plot <- lachesis

  if (clin.suppress.outliers) {
    to.plot <- to.plot[MRCA_time_mean < quantile(MRCA_time_mean, 0.975) &
                         MRCA_time_mean > quantile(MRCA_time_mean, 0.025), ]
  }
  # Correlation between SNV density and the clinical parameters
  to.plot <- to.plot[!is.na(get(clin.par)), ]
  if (nrow(to.plot) > 0) {
    par(mar = c(4, 4, 3, 1), xpd = FALSE)

    to.plot[, plot(MRCA_time_mean, get(clin.par),
                   xlab = NA, ylab = NA,
                   xlim = c(0, 1.05 * max(MRCA_time_mean)),
                   ylim = c(0, 1.05 * max(get(clin.par))), cex.axis = 0.7,
                   log = ifelse(clin.log.densities, "x", "")
    )]
    title(main = "SNV densities at MRCA vs age", cex.main = 1)
    mtext(text = "SNVs per Mb", side = 1, line = 2, cex = 0.8)
    mtext(text = clin.par, side = 2, line = 1.8, cex = 0.8)
    text(0.55 * 1.05 * max(to.plot[, MRCA_time_mean]),
         0.75 * max(to.plot[, get(clin.par)]),
         labels = paste(
           "Pearson's r = ",
           to.plot[, round(cor(MRCA_time_mean, get(clin.par)),
                           digits = 3
           )]
         ),
         cex = 0.8
    )

    par(mar = c(4, 4, 3, 1), xpd = FALSE)

    to.plot[, plot(ECA_time_mean, get(clin.par),
                   xlab = NA, ylab = NA,
                   xlim = c(0, 1.05 * max(ECA_time_mean, na.rm = TRUE)),
                   ylim = c(0, 1.05 * max(get(clin.par))), cex.axis = 0.7,
                   log = ifelse(clin.log.densities, "x", "")
    )]

    title(main = "SNV densities at ECA vs age", cex.main = 1)
    mtext(text = "SNVs per Mb", side = 1, line = 2, cex = 0.8)
    mtext(text = clin.par, side = 2, line = 1.8, cex = 0.8)
    text(0.5 * 1.05 * max(to.plot[, ECA_time_mean]),
         0.75 * max(to.plot[, get(clin.par)]),
         labels = paste(
           "Pearson's r = ",
           to.plot[, round(cor(ECA_time_mean, get(clin.par)),
                           digits = 3
           )]
         ),
         cex = 0.8
    )

  } else {
    # Empty plots
    plot.new()
    plot.new()
  }

  if (!is.null(output.file)) {
    dev.off()
  }
}
