#' Plot the disease trajectories in a cohort.
#' @description
#' Takes SNV densities as computed by `LACHESIS` as input and plots for each
#' case the estimated age at ECA, MRCA and the age at diagnosis.
#' @param lachesis output generated from \code{\link{LACHESIS}}.
#' @param mut.snv.rate optional; rate of accumulated SNVs per day in a
#' diploid genome (i.e. 3.2 SNVs/day in neuroblastoma)
#' @param lach.col.eca optional, color for ECA.
#' @param lach.col.mrca optional, color for MRCA.
#' @param corr.time.scale numeric value by which survival time is to be divided
#' to convert into months (e.g., 30 for converting days into months), defaults
#' to `1`.
#' @param output.file optional; file path to output.
#' @return graph with SNV densities and estimated times at ECA/ MRCA and
#' diagnosis.
#' @examples
#' # An example file with sample annotations and meta data
#' input.files <- system.file("extdata", "Sample_template.txt",
#'     package = "LACHESIS"
#' )
#' input.files <- data.table::fread(input.files)
#'
#' # cnv and snv files for example tumors
#' nbe11 <- list.files(system.file("extdata/NBE11/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe15 <- list.files(system.file("extdata/NBE15/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#' nbe26 <- list.files(system.file("extdata/NBE26/", package = "LACHESIS"),
#'     full.names = TRUE
#' )
#'
#' cnv.file <- c(nbe11[1], nbe15[1], nbe26[1])
#' snv.file <- c(nbe11[2], nbe15[2], nbe26[2])
#'
#' input.files$cnv.file <- cnv.file
#' input.files$snv.file <- snv.file
#'
#' # Make an example input file with paths to cnv and snv file along with other
#' # meta data
#' lachesis_input <- tempfile(
#'     pattern = "lachesis", tmpdir = tempdir(),
#'     fileext = ".tsv"
#' )
#' data.table::fwrite(x = input.files, file = lachesis_input, sep = "\t")
#'
#' # Example with template file with paths to multiple cnv/snv files as an input
#' lachesis <- LACHESIS(input.files = lachesis_input)
#' plotDiseaseTrajectories(lachesis, corr.time.scale = 31)
#' @export
#' @importFrom graphics abline Axis box grid hist mtext par rect text title
#' arrows points
#' @importFrom stats cor

plotDiseaseTrajectories <- function(lachesis = NULL, mut.snv.rate = 3.2,
                                     lach.col.eca = "#176A02",
                                     lach.col.mrca = "#4FB12B",
                                    corr.time.scale = 1,
                                     output.file = NULL) {
  ECA_time_mean <- MRCA_time_mean <- NULL


  if (is.null(lachesis)) {
    stop("Missing input. Please provide the output generated by LACHESIS()")
  }
  if (is.null(lachesis[["Age"]])){
    stop("Missing age information.")
  }
  if (any(is.na(lachesis$MRCA_time_mean))) {
    tmp1 <- sum(is.na(lachesis$MRCA_time_mean))
    warning(sprintf(
      "Removing %s samples with missing MRCA density estimate.", tmp1
    ))
    rm(tmp1)
    lachesis <- lachesis[!is.na(MRCA_time_mean), ]
  }
  if (nrow(lachesis) == 0) {
    warning(
      "No sample with MRCA density estimate provided. Returning zero."
    )
    return(NULL)
  }
  if (!is.null(output.file)) {
    pdf(output.file, width = 8, height = 6)
  }

    graphics::layout(matrix(1, 1, 1))

    to.plot <- lachesis[order(lachesis[["MRCA_time_mean"]]), ]

    age_months <- to.plot[["Age"]] / corr.time.scale
    # convert months into weeks (38 weeks of gestation)
    age_weeks_pc <- 38 + age_months * 4.345
    # convert to SNVs/Mb after gastrulation (2 weeks after conception)
    age_xaxis <- (age_weeks_pc - 2) * 7 * mut.snv.rate / (3300 * 2)

    n <- nrow(to.plot)
    y.pos <- seq_len(n)

    x.max <- max(
      to.plot[["MRCA_time_mean"]],
      to.plot[["ECA_time_mean"]],
      age_xaxis,
      na.rm = TRUE
    )
    x.min <- 0
    cex_id <- if(nrow(to.plot) > 45) 0.35 else 0.6
    cex_points <- if(nrow(to.plot) > 45) 0.7 else 1

    par(mar = c(3.5, 4, 4, 2), xpd = FALSE)

    plot(
      NA,
      xlim = c(x.min, 1.05 * x.max),
      ylim = c(0.5, n + 0.5),
      yaxt = "n",
      xlab = NA,
      ylab = "",
      cex.axis = 0.5
    )
    mtext(text = "SNVs per Mb", side = 1, line = 2, cex = 0.7)
    axis(
      side = 2,
      at = y.pos,
      labels = to.plot[["Sample_ID"]],
      las = 2,
      cex.axis = cex_id
    )
    title(main = "Real-Time Estimation at ECA/ MRCA vs Age at Diagnosis",
          cex.main = 1, line = 3)

    ## MRCA
    if ("MRCA_time_mean" %in% colnames(to.plot)) {
      points(
        to.plot[["MRCA_time_mean"]],
        y.pos,
        pch = 16,
        col = lach.col.mrca,
        cex = cex_points
      )
    }

    ## ECA
    if ("ECA_time_mean" %in% colnames(to.plot)) {
      to.plot_eca <- !is.na(to.plot[["ECA_time_mean"]])
      points(
        to.plot2[["ECA_time_mean"]][to.plot_eca],
        y.pos[to.plot_eca],
        pch = 16,
        col = lach.col.eca,
        cex = cex_points
      )

      segments(
        x0 = to.plot[["ECA_time_mean"]][to.plot_eca],
        y0 = y.pos[to.plot_eca],
        x1 = to.plot[["MRCA_time_mean"]][to.plot_eca],
        y1 = y.pos[to.plot_eca],
        col = "gray50",
        lty = 2
      )
    }

    ## Age
    to.plot_age <- !is.na(age_xaxis)
    points(
      age_xaxis[to.plot_age],
      y.pos[to.plot_age],
      pch = 16,
      col = "black",
      cex = cex_points
    )
    if ("MRCA_time_mean" %in% colnames(to.plot)) {
      segments(
        x0 = to.plot[["MRCA_time_mean"]][to.plot_age],
        y0 = y.pos[to.plot_age],
        x1 = age_xaxis[to.plot_age],
        y1 = y.pos[to.plot_age],
        col = "gray50",
        lty = 2
      )
    }

    # Quality check whether age at diagnosis is before the timing of MRCA
    age_before_mrca <- to.plot_age &
      !is.na(to.plot[["MRCA_time_mean"]]) &
      (age_xaxis < to.plot[["MRCA_time_mean"]])

    if (any(age_before_mrca, na.rm = TRUE)) {
      text(
        x = age_xaxis[age_before_mrca],
        y = y.pos[age_before_mrca],
        labels = "*",
        col = "red",
        pos = 4,
        cex = 1.1
      )
      mtext(
        "       * Diagnosis before timing of MRCA: doublecheck QC and
        confidence intervals",
        side = 0,
        line = 2,
        col = "red",
        cex = 0.6,
        adj = 0
      )
    }


    # the maximal time in units of six months:
    x.max.six.months <- x.max/ mut.snv.rate * 2 * 3300 / ( 6 * 30 )

    # step size such that there are maximally 10 ticks
    step.size <- ifelse(x.max.six.months > 10, 52, 26)
    weeks_pc <- c(12, 27, 38, 64, seq(2 * 26, x.max.six.months * 26,
                                      step.size) + 38)
    # Converting SNVs per day to SNVs per Mb starting from
    # gastrulation (-2 weeks), assuming haploid genome of 3300Mb
    snvs_per_mb <- (weeks_pc - 2) * 7 * mut.snv.rate / (3300 * 2)
    realtime_labels <- c(
      "12wk", "27wk", "38wk", "6mo",
      paste(seq(2 , x.max.six.months , 1/(26/step.size)) * 6, "mo", sep = "")
    )
    axis(
      side = 3,
      at = snvs_per_mb,
      labels = realtime_labels,
      cex.axis = 0.7
    )
    segments(
      x0 = x.min,
      y0 = par("usr")[4],
      x1 = 1.05 * x.max,
      y1 = par("usr")[4],
      xpd = NA
    )
    mtext(
      "Estimated time (weeks post conception and months postnatal)",
      side = 3,
      line = 2,
      cex = 0.7
    )
    legend(
      "bottomright",
      legend = c("MRCA", "ECA", "Age at diagnosis"),
      col = c(lach.col.mrca, lach.col.eca, "black"),
      pch = 16,
      cex = 0.7,
      bty = "n"
    )

  if (!is.null(output.file)) {
    dev.off()
  }
}
